/*
 * Rate Limit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"net/http"
)

// CachingApiRouter defines the required methods for binding the api requests to a responses for the CachingApi
// The CachingApiRouter implementation should parse necessary information from the http request,
// pass the data to a CachingApiServicer to perform the required actions, then write the service results to the http response.
type CachingApiRouter interface {
	CacheableGet(http.ResponseWriter, *http.Request)
}

// ErrorsApiRouter defines the required methods for binding the api requests to a responses for the ErrorsApi
// The ErrorsApiRouter implementation should parse necessary information from the http request,
// pass the data to a ErrorsApiServicer to perform the required actions, then write the service results to the http response.
type ErrorsApiRouter interface {
	ErrorsPercentGet(http.ResponseWriter, *http.Request)
}

// RateLimitingApiRouter defines the required methods for binding the api requests to a responses for the RateLimitingApi
// The RateLimitingApiRouter implementation should parse necessary information from the http request,
// pass the data to a RateLimitingApiServicer to perform the required actions, then write the service results to the http response.
type RateLimitingApiRouter interface {
	RateLimitByAccountGet(http.ResponseWriter, *http.Request)
	RateLimitByIpGet(http.ResponseWriter, *http.Request)
	RateLimitExponentialBackoffGet(http.ResponseWriter, *http.Request)
}

// CachingApiServicer defines the api actions for the CachingApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CachingApiServicer interface {
	CacheableGet(context.Context, string, int32, bool) (ImplResponse, error)
}

// ErrorsApiServicer defines the api actions for the ErrorsApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ErrorsApiServicer interface {
	ErrorsPercentGet(context.Context, int32) (ImplResponse, error)
}

// RateLimitingApiServicer defines the api actions for the RateLimitingApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type RateLimitingApiServicer interface {
	RateLimitByAccountGet(context.Context, string) (ImplResponse, error)
	RateLimitByIpGet(context.Context) (ImplResponse, error)
	RateLimitExponentialBackoffGet(context.Context) (ImplResponse, error)
}
